  host: '0.0.0.0'
port: 3500
document-root: '/Users/danielesalatti/Sites'
mime-types:
  '.bz'      : 'application/x-bzip'
  '.bz2'     : 'application/x-bzip2'
  '.css'     : 'text/css'
  '.dart'    : 'application/dart'
  '.exe'     : 'application/octet-stream'
  '.gif'     : 'image/gif'
  '.gz'      : 'application/x-gzip'
  '.html'    : 'text/html; charset=utf-8'
  '.jpg'     : 'image/jpeg'
  '.js'      : 'application/javascript'
  '.json'    : 'application/json'
  '.mp3'     : 'audio/mpeg'
  '.mp4'     : 'video/mp4'
  '.pdf'     : 'application/pdf'
  '.png'     : 'image/png'
  '.tar.gz'  : 'application/x-tar'
  '.tgz'     : 'application/x-tar'
  '.txt'     : 'text/plain; charset=utf-8'
  '.webp'    : 'image/webp'
  '.webm'    : 'video/webm'
  '.zip'     : 'application/zip' 
